UPDATE `creature_template` SET `KillCredit2`='0' WHERE  `entry`=158967;
UPDATE `creature_template` SET `dynamicflags`='0' WHERE  `entry`=180524;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=189038;
UPDATE `creature_template` SET `dynamicflags`='0' WHERE  `entry`=3281;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=185618;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=188391;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=188061;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=185996;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=186872;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=185848;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=186092;
UPDATE `creature_template` SET `KillCredit2`='0' WHERE  `entry`=159011;
UPDATE `creature_template` SET `KillCredit2`='0' WHERE  `entry`=158946;
UPDATE `creature_template` SET `KillCredit1`='0' WHERE  `entry`=129994;
UPDATE `creature_template` SET `KillCredit1`='0' WHERE  `entry`=130100;
UPDATE `creature_template` SET `KillCredit2`='0' WHERE  `entry`=164802;
UPDATE `creature_template` SET `KillCredit2`='0' WHERE  `entry`=163316;
UPDATE `creature_template` SET `KillCredit2`='0' WHERE  `entry`=165912;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=184846;
UPDATE `creature_template` SET `flags_extra`='0' WHERE  `entry`=36135;
UPDATE `creature_template` SET `faction`='35' WHERE  `entry`=185188;
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 0, 1, 'Enjoy! You won\'\'t find better ale anywhere!', 12, 0, 100, 0, 0, 0, 0, 5308, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 1, 1, 'Hey! Get away from that!', 14, 0, 100, 0, 0, 0, 0, 5053, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 1, 2, 'Hey! Stop that!', 14, 0, 100, 0, 0, 0, 0, 5056, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 1, 3, 'No stealing the goods!', 14, 0, 100, 0, 0, 0, 0, 5055, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 1, 4, 'Phalanx, I think you need to teach thos person a lesson.', 14, 0, 100, 0, 0, 0, 0, 5057, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 2, 0, 'Hey, my pockets were picked!', 14, 0, 100, 0, 0, 0, 0, 5266, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 2, 1, 'That\'\'s it! No more beer until this mess is sorted out!', 14, 0, 100, 0, 0, 0, 0, 5267, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 3, 0, 'That\'\'s it! You\'\'re going down!', 14, 0, 100, 0, 0, 0, 0, 5060, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 1, 0, 'What are you doing over there?', 14, 0, 100, 0, 0, 0, 0, 5054, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 0, 2, 'Have you tried the Dark Iron Ale? It\'\'s the best!', 12, 0, 100, 0, 0, 0, 0, 5309, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 0, 3, 'Try the boar! It\'\'s my new recipe!', 12, 0, 100, 0, 0, 0, 0, 5310, 0, 'Plugger_Spazzring');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (144129, 0, 0, 'Drink up! There\'\'s more where that came from!', 12, 0, 100, 0, 0, 0, 0, 5307, 0, 'Plugger_Spazzring');
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=144118;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=149626;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=160737;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=164098;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=168502;
UPDATE `smart_scripts` SET `event_param1`='0' WHERE  `entryorguid`=137354 AND `source_type`=0 AND `id`=0 AND `link`=1;
UPDATE `smart_scripts` SET `event_param1`='0' WHERE  `entryorguid`=137354 AND `source_type`=0 AND `id`=1 AND `link`=0;
UPDATE `smart_scripts` SET `action_param1`='1' WHERE  `entryorguid`=130742 AND `source_type`=0 AND `id`=2 AND `link`=0;
UPDATE `smart_scripts` SET `action_param1`='2' WHERE  `entryorguid`=130742 AND `source_type`=0 AND `id`=3 AND `link`=0;
UPDATE `smart_scripts` SET `event_param1`='0' WHERE  `entryorguid`=131174 AND `source_type`=0 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_param2`='131241' WHERE  `entryorguid`=131241 AND `source_type`=0 AND `id`=2 AND `link`=0;
UPDATE `smart_scripts` SET `event_flags`='0' WHERE  `entryorguid`=122973 AND `source_type`=0 AND `id`=1 AND `link`=0;
UPDATE `smart_scripts` SET `link`='0' WHERE  `entryorguid`=125862 AND `source_type`=0 AND `id`=7 AND `link`=7;
UPDATE `smart_scripts` SET `event_type`='19' WHERE  `entryorguid`=126713 AND `source_type`=0 AND `id`=8 AND `link`=0;
REPLACE INTO `creature_text` (`CreatureID`, `Text`, `Type`, `Probability`) VALUES ('127766', 'hmmpf I was expecting a bigger challenge', '12', '100');
UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI' WHERE  `entry`=269796;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=148233;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=156769;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=169524;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=173369;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=173370;
UPDATE `smart_scripts` SET `event_flags`='0' WHERE  `entryorguid`=131402 AND `source_type`=0 AND `id`=1 AND `link`=0;
UPDATE `smart_scripts` SET `event_flags`='0' WHERE  `entryorguid`=131492 AND `source_type`=0 AND `id`=2 AND `link`=0;
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (129088, 0, 1, 'Dis will take you to de chamber below where Princess Talanji is waiting for you. Mind de step.', 12, 0, 100, 0, 0, 0, 0, 135610, 0, 'Zolani <Blade of the King>');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (129088, 1, 0, 'Sígueme. Puedo llevarte por el camino más fácil.', 12, 0, 100, 1, 0, 0, 0, 0, 0, 'Zolani');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (129088, 2, 0, 'Este elevador te llevará a la cámara donde la princesa Talanji te eh\'tá esperando. Ten cuidado dónde pisas.', 12, 0, 100, 1, 0, 0, 0, 0, 0, 'Zolani');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (129088, 0, 0, 'Follow me. I can lead you to de easiest way down.', 12, 0, 100, 0, 0, 0, 0, 135604, 0, 'Zolani <Blade of the King>');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (105689, 1, 0, 'I found a vrykul saga describing a powerful shield Tyr crafted for his vrykul champion to carry into battle.', 12, 0, 100, 1, 0, 63273, 0, 114347, 0, '');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (105689, 2, 0, 'Aye, that\\\'s my hope. With your help, we have a chance of finding this artifact.', 12, 0, 100, 5, 0, 63275, 0, 114350, 0, '');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (105689, 3, 0, 'The tower in the middle o\\\' Dalaran has a portal to Wyrmrest Temple. Should get ye most o\\\' the way there. Tahu, thanks again fer helping us paladins.', 12, 0, 100, 1, 0, 63278, 0, 108609, 0, '');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (105689, 0, 0, 'The tower in the middle o\\\' Dalaran has a portal to Wyrmrest Temple. Should get ye most o\\\' the way there. Tahu, thanks again fer helping us paladins.', 12, 0, 100, 1, 0, 63272, 0, 114346, 0, '');
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=100696;
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (92620, 0, 0, 'Finish your business here, then meet me in the keep.', 12, 0, 100, 0, 0, 0, 0, 94794, 0, '');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (92620, 1, 0, 'When you\\\'re done, find me in the fortress..', 12, 0, 100, 0, 0, 52654, 0, 94794, 0, '');
REPLACE INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (93602, 0, 0, 'Be blessed, young one.', 12, 0, 100, 449, 0, 52278, 0, 95313, 0, '');