REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (38923, 0, 0, 1, 38, 0, 100, 0, 1, 1, 0, 0, 0, '', 33, 38887, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 0, 'Set Data Killcredit');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (38923, 0, 1, 0, 38, 0, 100, 0, 1, 1, 0, 0, 0, '', 44, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Link set Phase 2');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (38923, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, '', 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Link Despawn');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (38923, 0, 3, 0, 54, 0, 100, 0, 0, 0, 0, 0, 0, '', 29, 3, 0, 38925, 0, 0, 0, 18, 20, 0, 0, 0, 0, 0, 0, 0, 'Summo');

UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=38925;
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (38925, 0, 0, 0, 1, 0, 100, 0, 3000, 3000, 3000, 3000, 0, '', 45, 1, 1, 0, 0, 0, 0, 11, 38923, 5, 0, 0, 0, 0, 0, 0, 'Time 3s - Set Data Target (Quest 24974)');

UPDATE `smart_scripts` SET `link`='1', `action_type`='11', `action_param1`='73110', `action_param2`='0', `target_type`='7', `comment`='SpellHit - Summon Puddlejumper: Force Cast' WHERE  `entryorguid`=1543 AND `source_type`=0 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `link`='2', `event_type`='61', `event_param1`='0', `event_param2`='0', `event_param3`='0', `event_param4`='0', `action_type`='33', `action_param1`='38923', `target_type`='7', `comment`='Link - Kill Credit' WHERE  `entryorguid`=1543 AND `source_type`=0 AND `id`=1 AND `link`=0;
REPLACE INTO `smart_scripts` (`entryorguid`, `id`, `event_type`, `action_type`, `target_type`, `comment`) VALUES ('1543', '2', '61', '41', '1', 'Link - Despawn');
REPLACE INTO `smart_scripts` (`entryorguid`, `id`, `event_type`, `event_flags`, `event_param1`, `event_param2`, `action_type`, `action_param1`, `target_type`, `comment`) VALUES ('1543', '3', '9', '1', '5', '45', '11', '75002', '2', 'Cast');

UPDATE `smart_scripts` SET `event_type`='4', `event_flags`='1', `event_param1`='0', `action_type`='11', `action_param1`='12550', `action_param2`='0' WHERE  `entryorguid`=1544 AND `source_type`=0 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='4', `event_flags`='1', `event_param3`='0', `event_param4`='0', `action_param2`='0' WHERE  `entryorguid`=1544 AND `source_type`=0 AND `id`=1 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='9', `event_param1`='0', `event_param2`='40', `event_param3`='9200', `event_param4`='11400', `action_param1`='9532', `target_type`='2' WHERE  `entryorguid`=1544 AND `source_type`=0 AND `id`=2 AND `link`=0;

